<#
.SYNOPSIS
    Set environment variables for Docker Desktop deployment

.DESCRIPTION
    This script helps you set environment variables for your local Docker Desktop MCP services.
    It creates a .env file that docker-compose will use, or sets PowerShell environment variables.

.PARAMETER UseEnvFile
    Create/update a .env file instead of setting PowerShell environment variables

.PARAMETER GoogleApiKey
    Google API Key for mcp-tokenstats

.PARAMETER GoogleCloudProject
    Google Cloud Project ID for mcp-agent-inventory

.PARAMETER GcpProjectNumber
    Google Cloud Project Number for mcp-agent-inventory

.PARAMETER GcpLocation
    Google Cloud Location for mcp-agent-inventory (default: us-central1)

.PARAMETER ShowCurrent
    Show current environment variable values

.EXAMPLE
    .\set-docker-env-vars.ps1 -GoogleApiKey "your-api-key"

.EXAMPLE
    .\set-docker-env-vars.ps1 -UseEnvFile -GoogleApiKey "your-api-key"
#>

param(
    [switch]$UseEnvFile,
    [string]$GoogleApiKey = "",
    [string]$GoogleCloudProject = "",
    [string]$GcpProjectNumber = "",
    [string]$GcpLocation = "us-central1",
    [switch]$ShowCurrent
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ScriptDir

if ($ShowCurrent) {
    Write-Host "Current Environment Variables:" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "GOOGLE_API_KEY: $(if ($env:GOOGLE_API_KEY) { '***' + $env:GOOGLE_API_KEY.Substring($env:GOOGLE_API_KEY.Length - 4) } else { 'NOT SET' })" -ForegroundColor $(if ($env:GOOGLE_API_KEY) { "Green" } else { "Yellow" })
    Write-Host "GOOGLE_CLOUD_PROJECT: $($env:GOOGLE_CLOUD_PROJECT)" -ForegroundColor $(if ($env:GOOGLE_CLOUD_PROJECT) { "Green" } else { "Yellow" })
    Write-Host "GCP_PROJECT_NUMBER: $($env:GCP_PROJECT_NUMBER)" -ForegroundColor $(if ($env:GCP_PROJECT_NUMBER) { "Green" } else { "Yellow" })
    Write-Host "GOOGLE_CLOUD_LOCATION: $($env:GOOGLE_CLOUD_LOCATION)" -ForegroundColor $(if ($env:GOOGLE_CLOUD_LOCATION) { "Green" } else { "Yellow" })
    Write-Host ""
    
    if (Test-Path ".env") {
        Write-Host ".env file exists" -ForegroundColor Green
    } else {
        Write-Host ".env file does not exist" -ForegroundColor Yellow
    }
    exit 0
}

if ($UseEnvFile) {
    Write-Host "Creating/updating .env file..." -ForegroundColor Cyan
    Write-Host ""
    
    $envContent = @()
    
    # Get values from parameters or environment or defaults
    $apiKey = if ($GoogleApiKey) { $GoogleApiKey } else { $env:GOOGLE_API_KEY }
    $projectId = if ($GoogleCloudProject) { $GoogleCloudProject } else { $env:GOOGLE_CLOUD_PROJECT }
    $projectNumber = if ($GcpProjectNumber) { $GcpProjectNumber } else { $env:GCP_PROJECT_NUMBER }
    $location = if ($GcpLocation) { $GcpLocation } else { $env:GOOGLE_CLOUD_LOCATION }
    
    # Read existing .env if it exists
    if (Test-Path ".env") {
        $existingContent = Get-Content ".env"
        foreach ($line in $existingContent) {
            if ($line -match '^\s*#' -or $line -match '^\s*$') {
                $envContent += $line
                continue
            }
            if ($line -match '^GOOGLE_API_KEY=') {
                if ($apiKey) { $envContent += "GOOGLE_API_KEY=$apiKey" } else { $envContent += $line }
            } elseif ($line -match '^GOOGLE_CLOUD_PROJECT=') {
                if ($projectId) { $envContent += "GOOGLE_CLOUD_PROJECT=$projectId" } else { $envContent += $line }
            } elseif ($line -match '^GCP_PROJECT_NUMBER=') {
                if ($projectNumber) { $envContent += "GCP_PROJECT_NUMBER=$projectNumber" } else { $envContent += $line }
            } elseif ($line -match '^GOOGLE_CLOUD_LOCATION=') {
                if ($location) { $envContent += "GOOGLE_CLOUD_LOCATION=$location" } else { $envContent += $line }
            } else {
                $envContent += $line
            }
        }
    } else {
        # Create new .env file from template
        $envContent = @(
            "# Environment Variables for MCP Servers",
            "# Generated by set-docker-env-vars.ps1",
            "",
            "# Required for mcp-tokenstats"
        )
        if ($apiKey) {
            $envContent += "GOOGLE_API_KEY=$apiKey"
        } else {
            $envContent += "GOOGLE_API_KEY=your-google-api-key-here"
        }
        
        $envContent += ""
        $envContent += "# Required for mcp-agent-inventory"
        $envContent += "GOOGLE_CLOUD_PROJECT=$(if ($projectId) { $projectId } else { 'aiagent-capstoneproject' })"
        $envContent += "GCP_PROJECT_NUMBER=$(if ($projectNumber) { $projectNumber } else { '1276251306' })"
        $envContent += "GOOGLE_CLOUD_LOCATION=$(if ($location) { $location } else { 'us-central1' })"
        
        $envContent += ""
        $envContent += "# Optional for mcp-reasoning-cost"
        $envContent += "LLM_INPUT_TOKEN_PRICE_PER_M=1.25"
        $envContent += "LLM_OUTPUT_TOKEN_PRICE_PER_M=10.00"
    }
    
    # Add missing variables
    if (-not ($envContent -match '^GOOGLE_API_KEY=')) {
        $envContent += "GOOGLE_API_KEY=$(if ($apiKey) { $apiKey } else { 'your-google-api-key-here' })"
    }
    if (-not ($envContent -match '^GOOGLE_CLOUD_PROJECT=')) {
        $envContent += "GOOGLE_CLOUD_PROJECT=$(if ($projectId) { $projectId } else { 'aiagent-capstoneproject' })"
    }
    if (-not ($envContent -match '^GCP_PROJECT_NUMBER=')) {
        $envContent += "GCP_PROJECT_NUMBER=$(if ($projectNumber) { $projectNumber } else { '1276251306' })"
    }
    if (-not ($envContent -match '^GOOGLE_CLOUD_LOCATION=')) {
        $envContent += "GOOGLE_CLOUD_LOCATION=$(if ($location) { $location } else { 'us-central1' })"
    }
    
    $envContent | Set-Content ".env"
    Write-Host ".env file created/updated" -ForegroundColor Green
    Write-Host ""
    Write-Host "Note: docker-compose will automatically load this .env file" -ForegroundColor Cyan
    Write-Host "Restart containers to apply changes:" -ForegroundColor Yellow
    Write-Host "  docker compose down" -ForegroundColor Gray
    Write-Host "  docker compose up -d" -ForegroundColor Gray
} else {
    Write-Host "Setting PowerShell environment variables..." -ForegroundColor Cyan
    Write-Host ""
    
    # Set environment variables in current session
    if ($GoogleApiKey) {
        $env:GOOGLE_API_KEY = $GoogleApiKey
        Write-Host "✓ Set GOOGLE_API_KEY" -ForegroundColor Green
    } elseif (-not $env:GOOGLE_API_KEY) {
        Write-Host "WARNING: GOOGLE_API_KEY not set" -ForegroundColor Yellow
        Write-Host "  Set it with: `$env:GOOGLE_API_KEY = 'your-key'" -ForegroundColor Gray
    }
    
    if ($GoogleCloudProject) {
        $env:GOOGLE_CLOUD_PROJECT = $GoogleCloudProject
        Write-Host "✓ Set GOOGLE_CLOUD_PROJECT" -ForegroundColor Green
    } elseif (-not $env:GOOGLE_CLOUD_PROJECT) {
        Write-Host "WARNING: GOOGLE_CLOUD_PROJECT not set" -ForegroundColor Yellow
    }
    
    if ($GcpProjectNumber) {
        $env:GCP_PROJECT_NUMBER = $GcpProjectNumber
        Write-Host "✓ Set GCP_PROJECT_NUMBER" -ForegroundColor Green
    } elseif (-not $env:GCP_PROJECT_NUMBER) {
        Write-Host "WARNING: GCP_PROJECT_NUMBER not set" -ForegroundColor Yellow
    }
    
    if ($GcpLocation) {
        $env:GOOGLE_CLOUD_LOCATION = $GcpLocation
        Write-Host "✓ Set GOOGLE_CLOUD_LOCATION" -ForegroundColor Green
    }
    
    Write-Host ""
    Write-Host "Note: These are set for the current PowerShell session only" -ForegroundColor Cyan
    Write-Host "To make them persistent, add to your PowerShell profile or use -UseEnvFile" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Restart containers to apply changes:" -ForegroundColor Yellow
    Write-Host "  .\deploy-to-docker-desktop.ps1 -Stop" -ForegroundColor Gray
    Write-Host "  .\deploy-to-docker-desktop.ps1" -ForegroundColor Gray
}

Write-Host ""
Write-Host "Current values:" -ForegroundColor Cyan
Write-Host "GOOGLE_API_KEY: $(if ($env:GOOGLE_API_KEY) { 'SET (length: ' + $env:GOOGLE_API_KEY.Length + ')' } else { 'NOT SET' })" -ForegroundColor $(if ($env:GOOGLE_API_KEY) { "Green" } else { "Yellow" })
Write-Host "GOOGLE_CLOUD_PROJECT: $(if ($env:GOOGLE_CLOUD_PROJECT) { $env:GOOGLE_CLOUD_PROJECT } else { 'NOT SET' })" -ForegroundColor $(if ($env:GOOGLE_CLOUD_PROJECT) { "Green" } else { "Yellow" })
Write-Host "GCP_PROJECT_NUMBER: $(if ($env:GCP_PROJECT_NUMBER) { $env:GCP_PROJECT_NUMBER } else { 'NOT SET' })" -ForegroundColor $(if ($env:GCP_PROJECT_NUMBER) { "Green" } else { "Yellow" })
Write-Host "GOOGLE_CLOUD_LOCATION: $(if ($env:GOOGLE_CLOUD_LOCATION) { $env:GOOGLE_CLOUD_LOCATION } else { 'NOT SET' })" -ForegroundColor $(if ($env:GOOGLE_CLOUD_LOCATION) { "Green" } else { "Yellow" })
if (Test-Path ".env") {
    Write-Host ".env file exists" -ForegroundColor Green
} else {
    Write-Host ".env file does not exist" -ForegroundColor Yellow
}

