<#
.SYNOPSIS
    Interactive script to create .env file for Docker Desktop deployment

.DESCRIPTION
    This script prompts for all required environment variables and creates a .env file
    that docker-compose will automatically load.

.EXAMPLE
    .\setup-env-file.ps1
#>

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ScriptDir

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Docker Desktop Environment Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env already exists
if (Test-Path ".env") {
    Write-Host "WARNING: .env file already exists" -ForegroundColor Yellow
    $overwrite = Read-Host "Overwrite existing .env file? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Cancelled. Existing .env file preserved." -ForegroundColor Yellow
        exit 0
    }
    Write-Host ""
}

Write-Host "Please provide the following environment variables:" -ForegroundColor Cyan
Write-Host ""

# Get GOOGLE_API_KEY
$apiKey = $env:GOOGLE_API_KEY
if ($apiKey) {
    Write-Host "GOOGLE_API_KEY found in environment" -ForegroundColor Green
    $use = Read-Host "Use existing value? (Y/n)"
    if ($use -eq "n" -or $use -eq "N") {
        $apiKey = Read-Host "Enter GOOGLE_API_KEY" -AsSecureString
        $BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($apiKey)
        $apiKey = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
    }
} else {
    Write-Host "GOOGLE_API_KEY (required for mcp-tokenstats):" -ForegroundColor Yellow
    $apiKeySecure = Read-Host "Enter GOOGLE_API_KEY" -AsSecureString
    $BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($apiKeySecure)
    $apiKey = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
}

Write-Host ""

# Get GOOGLE_CLOUD_PROJECT
$projectId = $env:GOOGLE_CLOUD_PROJECT
if (-not $projectId) {
    $projectId = Read-Host "Enter GOOGLE_CLOUD_PROJECT (default: aiagent-capstoneproject)"
    if ([string]::IsNullOrWhiteSpace($projectId)) {
        $projectId = "aiagent-capstoneproject"
    }
} else {
    Write-Host "GOOGLE_CLOUD_PROJECT found in environment: $projectId" -ForegroundColor Green
    $use = Read-Host "Use existing value? (Y/n)"
    if ($use -eq "n" -or $use -eq "N") {
        $projectId = Read-Host "Enter GOOGLE_CLOUD_PROJECT (default: aiagent-capstoneproject)"
        if ([string]::IsNullOrWhiteSpace($projectId)) {
            $projectId = "aiagent-capstoneproject"
        }
    }
}

Write-Host ""

# Get GCP_PROJECT_NUMBER
$projectNumber = $env:GCP_PROJECT_NUMBER
if (-not $projectNumber) {
    $projectNumber = Read-Host "Enter GCP_PROJECT_NUMBER (default: 1276251306)"
    if ([string]::IsNullOrWhiteSpace($projectNumber)) {
        $projectNumber = "1276251306"
    }
} else {
    Write-Host "GCP_PROJECT_NUMBER found in environment: $projectNumber" -ForegroundColor Green
    $use = Read-Host "Use existing value? (Y/n)"
    if ($use -eq "n" -or $use -eq "N") {
        $projectNumber = Read-Host "Enter GCP_PROJECT_NUMBER (default: 1276251306)"
        if ([string]::IsNullOrWhiteSpace($projectNumber)) {
            $projectNumber = "1276251306"
        }
    }
}

Write-Host ""

# Get GOOGLE_CLOUD_LOCATION
$location = $env:GOOGLE_CLOUD_LOCATION
if (-not $location) {
    $location = Read-Host "Enter GOOGLE_CLOUD_LOCATION (default: us-central1)"
    if ([string]::IsNullOrWhiteSpace($location)) {
        $location = "us-central1"
    }
} else {
    Write-Host "GOOGLE_CLOUD_LOCATION found in environment: $location" -ForegroundColor Green
    $use = Read-Host "Use existing value? (Y/n)"
    if ($use -eq "n" -or $use -eq "N") {
        $location = Read-Host "Enter GOOGLE_CLOUD_LOCATION (default: us-central1)"
        if ([string]::IsNullOrWhiteSpace($location)) {
            $location = "us-central1"
        }
    }
}

Write-Host ""

# Create .env file
$envContent = @(
    "# Environment Variables for MCP Servers",
    "# Generated by setup-env-file.ps1",
    "# DO NOT commit this file to version control",
    "",
    "# Required for mcp-tokenstats",
    "GOOGLE_API_KEY=$apiKey",
    "",
    "# Required for mcp-agent-inventory",
    "GOOGLE_CLOUD_PROJECT=$projectId",
    "GCP_PROJECT_NUMBER=$projectNumber",
    "GOOGLE_CLOUD_LOCATION=$location",
    "",
    "# Optional for mcp-reasoning-cost (defaults shown)",
    "LLM_INPUT_TOKEN_PRICE_PER_M=1.25",
    "LLM_OUTPUT_TOKEN_PRICE_PER_M=10.00"
)

$envContent | Set-Content ".env" -Encoding UTF8

Write-Host "========================================" -ForegroundColor Green
Write-Host "  .env file created successfully!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Review the .env file if needed" -ForegroundColor Gray
Write-Host "  2. Deploy containers: .\deploy-to-docker-desktop.ps1" -ForegroundColor Gray
Write-Host "  3. Or restart existing containers: .\deploy-to-docker-desktop.ps1 -Stop; .\deploy-to-docker-desktop.ps1" -ForegroundColor Gray
Write-Host ""
Write-Host "Note: .env file is automatically loaded by docker-compose" -ForegroundColor Yellow

